DROP TABLE IF EXISTS `album`;

CREATE TABLE `album` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `artist` varchar(100) NOT NULL,
  `title` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `album` WRITE;
/*!40000 ALTER TABLE `album` DISABLE KEYS */;

INSERT INTO `album` (`id`, `artist`, `title`)
VALUES
	(4,'Lana  Del  Rey','Born  To  Die'),
	(5,'Gotye','Making  Mirrors'),
	(6,'Wintersun','Sons of winter and stars'),
	(9,'metallica','Unforgiven II'),
	(10,'Scorpions','Wind of change'),
	(11,'Scorpions','Rock you like a hurricane'),
	(12,'Ghost Brigade','cult of decay'),
	(13,'Opeth','death whispered by a lullaby'),
	(14,'David Bowie','The Next Day (Deluxe Version)'),
	(15,'Bastille','Bad Blood'),
	(16,'Bruno Mars','Unorthodox Jukebox'),
	(17,'Emeli Sandé','Our Version of Events (Special Edition)'),
	(18,'Bon Jovi','What About Now (Deluxe Version)'),
	(19,'Justin Timberlake','The 20/20 Experience (Deluxe Version)'),
	(20,'Bastille','Bad Blood (The Extended Cut)'),
	(21,'P!nk','The Truth About Love'),
	(22,'Sound City - Real to Reel','Sound City - Real to Reel'),
	(23,'Jake Bugg','Jake Bugg'),
	(24,'Various Artists','The Trevor Nelson Collection'),
	(25,'David Bowie','The Next Day'),
	(26,'Mumford & Sons','Babel'),
	(27,'The Lumineers','The Lumineers'),
	(28,'Various Artists','Get Ur Freak On - R&B Anthems'),
	(29,'The 1975','Music For Cars EP'),
	(30,'Various Artists','Saturday Night Club Classics - Ministry of Sound'),
	(31,'Hurts','Exile (Deluxe)'),
	(32,'Various Artists','Mixmag - The Greatest Dance Tracks of All Time'),
	(33,'Ben Howard','Every Kingdom'),
	(34,'Stereophonics','Graffiti On the Train'),
	(35,'The Script','#3'),
	(36,'Stornoway','Tales from Terra Firma'),
	(37,'David Bowie','Hunky Dory (Remastered)'),
	(38,'Worship Central','Let It Be Known (Live)'),
	(39,'Ellie Goulding','Halcyon'),
	(40,'Various Artists','Dermot O\'Leary Presents the Saturday Sessions 2013'),
	(41,'Stereophonics','Graffiti On the Train (Deluxe Version)'),
	(42,'Dido','Girl Who Got Away (Deluxe)'),
	(43,'Hurts','Exile'),
	(44,'Bruno Mars','Doo-Wops & Hooligans'),
	(45,'Calvin Harris','18 Months'),
	(46,'Olly Murs','Right Place Right Time'),
	(47,'Alt-J (?)','An Awesome Wave'),
	(48,'One Direction','Take Me Home'),
	(49,'Various Artists','Pop Stars'),
	(50,'Various Artists','Now That\'s What I Call Music! 83'),
	(51,'John Grant','Pale Green Ghosts'),
	(52,'Paloma Faith','Fall to Grace'),
	(53,'Laura Mvula','Sing To the Moon (Deluxe)'),
	(54,'Duke Dumont','Need U (100%) [feat. A*M*E] - EP'),
	(55,'Watsky','Cardboard Castles'),
	(56,'Blondie','Blondie: Greatest Hits'),
	(57,'Foals','Holy Fire'),
	(58,'Maroon 5','Overexposed'),
	(59,'Bastille','Pompeii (Remixes) - EP'),
	(60,'Imagine Dragons','Hear Me - EP'),
	(61,'Various Artists','100 Hits: 80s Classics'),
	(62,'Various Artists','Les Misérables (Highlights From the Motion Picture Soundtrack)'),
	(63,'Mumford & Sons','Sigh No More'),
	(64,'Frank Ocean','Channel ORANGE'),
	(65,'Bon Jovi','What About Now'),
	(66,'Various Artists','BRIT Awards 2013'),
	(67,'Taylor Swift','Red'),
	(68,'Fleetwood Mac','Fleetwood Mac: Greatest Hits'),
	(69,'David Guetta','Nothing But the Beat Ultimate'),
	(70,'Various Artists','Clubbers Guide 2013 (Mixed By Danny Howard) - Ministry of Sound'),
	(71,'David Bowie','Best of Bowie'),
	(72,'Laura Mvula','Sing To the Moon'),
	(74,'Of Monsters and Men','My Head Is an Animal'),
	(75,'Rihanna','Unapologetic'),
	(76,'Various Artists','BBC Radio 1\'s Live Lounge - 2012'),
	(77,'Avicii & Nicky Romero','I Could Be the One (Avicii vs. Nicky Romero)'),
	(78,'The Streets','A Grand Don\'t Come for Free'),
	(79,'Tim McGraw','Two Lanes of Freedom'),
	(80,'Foo Fighters','Foo Fighters: Greatest Hits'),
	(81,'Various Artists','Now That\'s What I Call Running!'),
	(82,'Swedish House Mafia','Until Now'),
	(83,'The xx','Coexist'),
	(84,'Five','Five: Greatest Hits'),
	(85,'Jimi Hendrix','People, Hell & Angels'),
	(86,'Biffy Clyro','Opposites (Deluxe)'),
	(87,'The Smiths','The Sound of the Smiths'),
	(88,'The Saturdays','What About Us - EP'),
	(89,'Fleetwood Mac','Rumours'),
	(90,'Various Artists','The Big Reunion'),
	(91,'Various Artists','Anthems 90s - Ministry of Sound'),
	(92,'The Vaccines','Come of Age'),
	(93,'Nicole Scherzinger','Boomerang (Remixes) - EP'),
	(94,'Bob Marley','Legend (Bonus Track Version)'),
	(95,'Josh Groban','All That Echoes'),
	(96,'Blue','Best of Blue'),
	(97,'Ed Sheeran','+'),
	(98,'Olly Murs','In Case You Didn\'t Know (Deluxe Edition)'),
	(99,'Macklemore & Ryan Lewis','The Heist (Deluxe Edition)'),
	(100,'Various Artists','Defected Presents Most Rated Miami 2013'),
	(101,'Gorgon City','Real EP'),
	(102,'Mumford & Sons','Babel (Deluxe Version)'),
	(103,'Various Artists','The Music of Nashville: Season 1, Vol. 1 (Original Soundtrack)'),
	(104,'Various Artists','The Twilight Saga: Breaking Dawn, Pt. 2 (Original Motion Picture Soundtrack)'),
	(105,'Various Artists','Mum - The Ultimate Mothers Day Collection'),
	(106,'One Direction','Up All Night'),
	(107,'Bon Jovi','Bon Jovi Greatest Hits'),
	(108,'Agnetha Fältskog','A'),
	(109,'Fun.','Some Nights'),
	(110,'Justin Bieber','Believe Acoustic'),
	(111,'Atoms for Peace','Amok'),
	(112,'Justin Timberlake','Justified'),
	(113,'Passenger','All the Little Lights'),
	(114,'Kodaline','The High Hopes EP'),
	(115,'Lana Del Rey','Born to Die'),
	(116,'JAY Z & Kanye West','Watch the Throne (Deluxe Version)'),
	(117,'Biffy Clyro','Opposites'),
	(118,'Various Artists','Return of the 90s'),
	(119,'Gabrielle Aplin','Please Don\'t Say You Love Me - EP'),
	(120,'Various Artists','100 Hits - Driving Rock'),
	(121,'Jimi Hendrix','Experience Hendrix - The Best of Jimi Hendrix'),
	(122,'Various Artists','The Workout Mix 2013'),
	(123,'The 1975','Sex'),
	(124,'Chase & Status','No More Idols'),
	(125,'Rihanna','Unapologetic (Deluxe Version)'),
	(126,'The Killers','Battle Born'),
	(127,'Olly Murs','Right Place Right Time (Deluxe Edition)'),
	(128,'A$AP Rocky','LONG.LIVE.A$AP (Deluxe Version)'),
	(129,'Various Artists','Cooking Songs'),
	(130,'Haim','Forever - EP'),
	(131,'Lianne La Havas','Is Your Love Big Enough?'),
	(132,'Michael Bublé','To Be Loved'),
	(133,'Daughter','If You Leave'),
	(134,'The xx','xx'),
	(135,'Eminem','Curtain Call'),
	(136,'Kendrick Lamar','good kid, m.A.A.d city (Deluxe)'),
	(137,'Disclosure','The Face - EP'),
	(138,'Palma Violets','180'),
	(139,'Cody Simpson','Paradise'),
	(140,'Ed Sheeran','+ (Deluxe Version)'),
	(141,'Michael Bublé','Crazy Love (Hollywood Edition)'),
	(142,'Bon Jovi','Bon Jovi Greatest Hits - The Ultimate Collection'),
	(143,'Rita Ora','Ora'),
	(144,'g33k','Spabby'),
	(145,'Various Artists','Annie Mac Presents 2012'),
	(146,'David Bowie','The Platinum Collection'),
	(147,'Bridgit Mendler','Ready or Not (Remixes) - EP'),
	(148,'Dido','Girl Who Got Away'),
	(149,'Various Artists','Now That\'s What I Call Disney'),
	(150,'The 1975','Facedown - EP'),
	(151,'Kodaline','The Kodaline - EP'),
	(152,'Various Artists','100 Hits: Super 70s'),
	(153,'Fred V & Grafix','Goggles - EP'),
	(154,'Biffy Clyro','Only Revolutions (Deluxe Version)'),
	(155,'Train','California 37'),
	(156,'Ben Howard','Every Kingdom (Deluxe Edition)'),
	(157,'Various Artists','Motown Anthems'),
	(158,'Courteeners','ANNA'),
	(159,'Johnny Marr','The Messenger'),
	(160,'Rodriguez','Searching for Sugar Man'),
	(161,'Jessie Ware','Devotion'),
	(162,'Bruno Mars','Unorthodox Jukebox'),
	(163,'Various Artists','Call the Midwife (Music From the TV Series)'),
	(164,'Amon Amarth','Embrace of the endless ocean'),
	(165,'Wintersun','Land of snow and sorrow'),
	(166,'Deathklok','Awaken'),
	(167,'Lamb of god','11th hour'),
	(169,'Lamb of god','omerta'),
	(170,'Megadeth','Family tree'),
	(172,'Megadeth','hanger 18'),
	(173,'Amon Amarth','Death in fire'),
	(174,'Insomnium','Through the shadows'),
	(176,'the beatles','blackbird'),
	(187,'Tool','Schism'),
	(188,'metallica','mama said');
